server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name provider.example.com;

    ssl_certificate /etc/letsencrypt/live/provider.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/provider.example.com/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:9093;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Origin $http_origin;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 95s;
    }
}
