FROM python:3.13-alpine@sha256:399babc8b49529dabfd9c922f2b5eea81d611e4512e3ed250d75bd2e7683f4b0

COPY alert_sink.py /usr/local/libexec/immortal-provider-alert-sink
COPY esplora_broadcast.py /usr/local/libexec/immortal-lab-esplora-broadcast

ENTRYPOINT ["python3", "/usr/local/libexec/immortal-provider-alert-sink"]
